# Exercise 1: Tensor Creation
PyTorch Fundamentals - Module 1

This exercise covers:
- Creating tensors from different sources
- Understanding tensor attributes
- Creating tensors with specific values

PyTorch 2.0 Note: All code in this file is compatible with PyTorch 2.0.
See Exercise 5 for PyTorch 2.0 device management patterns.


In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'2.10.0+cpu'

In [3]:
np.__version__

'2.4.1'

## Part 1: Creating Tensors from Data

Create a scalar tensor (0-dimensional)

In [8]:
scalar = torch.tensor(7)
f"Scalar: {scalar}"

'Scalar: 7'

In [11]:
f"Scalar ndim: {scalar.ndim}"

'Scalar ndim: 0'

Create a vector tensor (1-dimensional)

In [12]:
vector = torch.tensor([1, 2, 3, 4, 5])
f"Vector: {vector}"

'Vector: tensor([1, 2, 3, 4, 5])'

In [13]:
f"Vector shape: {vector.shape}"

'Vector shape: torch.Size([5])'

Create a matrix tensor (2-dimensional)

In [14]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"\nMatrix:\n{matrix}")


Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [15]:
matrix.shape

torch.Size([2, 3])

Create a 3D tensor

In [16]:
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"\n3D Tensor:\n{tensor_3d}")


3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [17]:
f"3D Tensor shape: {tensor_3d.shape}"

'3D Tensor shape: torch.Size([2, 2, 2])'

## Part 2: Creating Tensors with Specific Values

Create a tensor filled with zeros

In [18]:
zeros = torch.zeros(3, 4)
print(f"Zeros (3x4):\n{zeros}")

Zeros (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Create a tensor filled with ones

In [19]:
ones = torch.ones(2, 3)
print(f"\nOnes (2x3):\n{ones}")


Ones (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])


Create a tensor filled with a specific value

In [20]:
full = torch.full((2, 3), 7)
print(f"\nFull with 7s (2x3):\n{full}")


Full with 7s (2x3):
tensor([[7, 7, 7],
        [7, 7, 7]])


Create identity matrix

In [21]:
identity = torch.eye(4)
print(f"\nIdentity matrix (4x4):\n{identity}")


Identity matrix (4x4):
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


Create a tensor with values from 0 to 9

In [22]:
range_tensor = torch.arange(0, 10)
print(f"\nRange (0-9):\n{range_tensor}")


Range (0-9):
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Create evenly spaced values

In [23]:
linspace = torch.linspace(0, 10, steps=5)
print(f"\nLinspace (0-10, 5 steps):\n{linspace}")


Linspace (0-10, 5 steps):
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


## Part 3: Creating Random Tensors

Set random seed for reproducibility

In [24]:
torch.manual_seed(42)

Create random tensor from uniform distribution [0, 1)

In [25]:
rand_uniform = torch.rand(3, 4)
print(f"Random uniform (3x4):\n{rand_uniform}")

Random uniform (3x4):
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


Create random tensor from normal distribution

In [26]:
rand_normal = torch.randn(2, 3)
print(f"\nRandom normal (2x3):\n{rand_normal}")


Random normal (2x3):
tensor([[ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094]])


Create random integers

In [27]:
rand_int = torch.randint(low=0, high=10, size=(3, 3))
print(f"\nRandom integers (0-9, 3x3):\n{rand_int}")


Random integers (0-9, 3x3):
tensor([[9, 3, 1],
        [9, 7, 9],
        [2, 0, 5]])


## Part 4: Working with NumPy

Create a NumPy array

In [28]:
np_array = np.array([[1, 2, 3], [4, 5, 6]])
print(f"NumPy array:\n{np_array}")

NumPy array:
[[1 2 3]
 [4 5 6]]


In [29]:
type(np_array)

numpy.ndarray

Convert NumPy array to PyTorch tensor

In [30]:
tensor_from_np = torch.from_numpy(np_array)
print(f"\nTensor from NumPy:\n{tensor_from_np}")


Tensor from NumPy:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [31]:
type(tensor_from_np)

torch.Tensor

Convert PyTorch tensor to NumPy array

In [32]:
np_from_tensor = tensor_from_np.numpy()
print(f"\nNumPy from tensor:\n{np_from_tensor}")


NumPy from tensor:
[[1 2 3]
 [4 5 6]]


In [33]:
type(np_from_tensor)

numpy.ndarray

## Part 5: Tensor attributes

In [35]:
tensor = torch.randn(2, 3, 4)

Print tensor shape

In [36]:
f"Shape: {tensor.shape}"

'Shape: torch.Size([2, 3, 4])'

Print tensor data type

In [37]:
f"Dtype: {tensor.dtype}"

'Dtype: torch.float32'

Print tensor device

In [38]:
f"Device: {tensor.device}"

'Device: cpu'

Print number of dimensions

In [39]:
f"Number of dimensions: {tensor.ndim}"

'Number of dimensions: 3'

Print total number of elements

In [40]:
f"Total elements: {tensor.numel()}"

'Total elements: 24'

## Exercises

Exercise 1: Create a 4x4 tensor filled with the value 3.14

In [44]:
tensor_4x4_314 = torch.full((4, 4), 3.14)
print(f"4x4 tensor filled with the value 3.14:\n{tensor_4x4_314}")

4x4 tensor filled with the value 3.14:
tensor([[3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400]])


Exercise 2: Create a random tensor of shape (5, 5) with values between 0 and 1

In [49]:
tensor_5x5_0_1 = torch.rand(5, 5)
print(f"5x5 tensor with values between 0 and 1:\n{tensor_5x5_0_1}")

5x5 tensor with values between 0 and 1:
tensor([[0.2234, 0.2469, 0.4761, 0.7792, 0.3722],
        [0.2147, 0.3288, 0.1265, 0.6783, 0.8870],
        [0.0293, 0.6161, 0.7583, 0.5907, 0.3219],
        [0.7610, 0.7628, 0.6870, 0.4121, 0.3676],
        [0.5535, 0.4117, 0.3510, 0.8196, 0.9297]])


Exercise 3: Create a tensor with values from 10 to 50 (exclusive) with step 5

In [50]:
linspace_10_50_step_5 = torch.linspace(start=10, end=50, steps=5)
print(f"Linspace from 10 to 50 with step 5:\n{linspace_10_50_step_5}")

Linspace from 10 to 50 with step 5:
tensor([10., 20., 30., 40., 50.])


Exercise 4: Create a 3D tensor of shape (2, 3, 4) filled with ones

In [52]:
tensor_2_3_4_ones = torch.ones(2, 3, 4)
print(f"3D tensor of shape (2, 3, 4) filled with ones:\n{tensor_2_3_4_ones}")

3D tensor of shape (2, 3, 4) filled with ones:
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [53]:
tensor_2_3_4_ones.shape

torch.Size([2, 3, 4])

Exercise 5: Check if a GPU is available and create a tensor on it if possible

In [54]:
if torch.cuda.is_available():
    tensor_gpu = torch.ones_like(tensor_4x4_314, device="cuda")
    print(f"Tensor on GPU:\n{tensor_gpu}")
else:
    tensor_cpu = torch.zeros(2, 3, 4)
    print(f"Tensor on CPU:\n{tensor_cpu}")

Tensor on CPU:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
