# Exercise 2: Tensor Operations
**PyTorch Fundamentals - Module 1**

This exercise covers:
- Basic arithmetic operations
- Matrix operations
- Reduction operations
- Comparison operations

PyTorch 2.0 Note: All operations in this file are compatible with PyTorch 2.0.
The @ operator for matrix multiplication is recommended for both PyTorch 1.x and 2.0.

In [1]:
import torch

In [2]:
torch.manual_seed(42)

## Part 1: Basic Arithmetic Operations

**Create test tensors**

In [3]:
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([5, 6, 7, 8], dtype=torch.float32)

In [4]:
x

tensor([1., 2., 3., 4.])

In [5]:
y

tensor([5., 6., 7., 8.])

**Addition**

In [8]:
add_result = x + y
print(f"\nAddition (x + y):\n\t{add_result}")


Addition (x + y):
	tensor([ 6.,  8., 10., 12.])


**Subtraction**

In [9]:
sub_result = x - y
print(f"Subtraction (x - y):\n\t{sub_result}")

Subtraction (x - y):
	tensor([-4., -4., -4., -4.])


**Element-wise multiplication**

In [10]:
mul_result = x * y
print(f"Multiplication (x * y):\n\t{mul_result}")

Multiplication (x * y):
	tensor([ 5., 12., 21., 32.])


**Element-wise division**

In [11]:
div_result = x / y
print(f"Division (x / y):\n\t{div_result}")

Division (x / y):
	tensor([0.2000, 0.3333, 0.4286, 0.5000])


**Power**

In [12]:
pow_result = x ** 2
print(f"Power (x^2):\n\t{pow_result}")

Power (x^2):
	tensor([ 1.,  4.,  9., 16.])


## Part 2: Matrix Operations

**Create matrices**

In [13]:
A = torch.randn(3, 4)
B = torch.randn(4, 5)

In [16]:
print(A)

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])


In [17]:
print(B)

tensor([[ 0.3559, -0.6866, -0.4934,  0.2415,  1.3123],
        [ 0.6872, -1.0892, -0.3553, -0.9138, -0.6581],
        [ 0.0780,  0.5258,  1.1790, -0.4345, -1.3864],
        [-1.2862, -1.4032,  0.0360, -0.0635,  0.6756]])


In [14]:
print(f"Matrix A shape: {A.shape}")
print(f"Matrix B shape: {B.shape}")

Matrix A shape: torch.Size([3, 4])
Matrix B shape: torch.Size([4, 5])


**Matrix multiplication**

In [18]:
matmul_result = A @ B
print(f"\nMatrix multiplication A @ B shape: {matmul_result.shape}")


Matrix multiplication A @ B shape: torch.Size([3, 5])


In [20]:
print(matmul_result)

tensor([[-0.0696, -0.5714,  0.0728, -0.1529,  0.1876],
        [ 0.4653,  3.0303,  3.2006, -1.0197, -4.8433],
        [-0.6513, -1.4626,  0.3370, -0.4166,  0.2351]])


**Transpose**

In [21]:
A_T = A.T
print(f"Transpose of A shape: {A_T.shape}")

Transpose of A shape: torch.Size([4, 3])


In [22]:
print(A_T)

tensor([[ 0.3367, -1.1229,  0.4617],
        [ 0.1288, -0.1863,  0.2674],
        [ 0.2345,  2.2082,  0.5349],
        [ 0.2303, -0.6380,  0.8094]])


**Element-wise min/max**

In [23]:
min_val = torch.min(A)
max_val = torch.max(A)

In [24]:
print(f"\nMin value in A: {min_val:.4f}")
print(f"Max value in A: {max_val:.4f}")


Min value in A: -1.1229
Max value in A: 2.2082


## Part 3: Reduction Operations

**Create a 2D tensor**

In [25]:
tensor = torch.randn(3, 4)
print(f"Tensor:\n{tensor}")

Tensor:
tensor([[-0.0085,  0.7291,  0.1331,  0.8640],
        [-1.0157, -0.8887,  0.1498, -0.2089],
        [-0.3870,  0.9912,  0.4679, -0.2049]])


**Sum all elements**

In [26]:
sum_all = torch.sum(tensor)
print(f"\nSum of all elements: {sum_all:.4f}")


Sum of all elements: 0.6213


**Sum along rows (dim=0)**

In [28]:
sum_rows = torch.sum(tensor, dim=0)
print(f"Sum along rows: {sum_rows}")

Sum along rows: tensor([-1.4112,  0.8315,  0.7508,  0.4502])


**Sum along columns (dim=1)**

In [29]:
sum_cols = torch.sum(tensor, dim=1)
print(f"Sum along columns: {sum_cols}")

Sum along columns: tensor([ 1.7177, -1.9635,  0.8672])


**Mean**

In [31]:
mean_all = torch.mean(tensor)
print(f"\nMean of all elements: {mean_all:.4f}")
print(mean_all == sum_all / tensor.numel())


Mean of all elements: 0.0518
tensor(True)


**Standard deviation**

In [32]:
std_all = torch.std(tensor)
print(f"Standard deviation: {std_all:.4f}")

Standard deviation: 0.6428


## Part 4: Comparison Operations

In [33]:
x = torch.tensor([1, 2, 3, 4, 5])
y = torch.tensor([2, 2, 4, 4, 6])

print(f"x: {x}")
print(f"y: {y}")

x: tensor([1, 2, 3, 4, 5])
y: tensor([2, 2, 4, 4, 6])


**Element-wise comparison**

In [34]:
eq_result = x == y
print(f"\nEqual (x == y): {eq_result}")


Equal (x == y): tensor([False,  True, False,  True, False])


In [35]:
gt_result = x > y
print(f"Greater than (x > y): {gt_result}")

Greater than (x > y): tensor([False, False, False, False, False])


In [36]:
lt_result = x < y
print(f"Less than (x < y): {lt_result}")

Less than (x < y): tensor([ True, False,  True, False,  True])


**Clamp values**

In [37]:
clamped = torch.clamp(x, min=2, max=4)
print(f"\nClamp x to [2, 4]: {clamped}")


Clamp x to [2, 4]: tensor([2, 2, 3, 4, 4])


In [38]:
clamped_y = torch.clamp(y, min=5, max=9)
print(f"Clamp y to [5, 9]: {clamped_y}")

Clamp y to [5, 9]: tensor([5, 5, 5, 5, 6])


## Part 5: Broadcasting

**Create tensors with different shapes**

In [39]:
x = torch.randn(3, 1)
y = torch.randn(1, 4)

print(f"x shape: {x.shape}")
print(f"y shape: {y.shape}")

x shape: torch.Size([3, 1])
y shape: torch.Size([1, 4])


In [49]:
print(x, y, sep="\n\n")

tensor([[-0.7409],
        [ 0.3618],
        [ 1.9199]])

tensor([[-0.2254, -0.3417,  0.3040, -0.6890]])


**Broadcast addition**

In [40]:
result = x + y
print(f"\nBroadcast result shape: {result.shape}")
print(f"Result:\n{result}")


Broadcast result shape: torch.Size([3, 4])
Result:
tensor([[-0.9663, -1.0826, -0.4369, -1.4299],
        [ 0.1365,  0.0201,  0.6659, -0.3272],
        [ 1.6945,  1.5782,  2.2239,  1.2309]])


## Exercise

**Exercise 1: Given two matrices A (4x3) and B (3x5), compute C = A @ B**

In [50]:
A = torch.randn(4, 3)
B = torch.randn(3, 5)

In [62]:
print(A, B, sep="\n\n")

tensor([[-1.1267, -0.2858, -1.0935],
        [ 1.1351,  0.7592, -3.5945],
        [ 0.0192,  0.1052,  0.9603],
        [-0.5672, -0.5706,  1.5980]])

tensor([[ 0.1115, -0.0392,  1.4112, -0.6556,  0.8576],
        [-1.6270, -1.3951, -0.2387, -0.5050, -2.4752],
        [-0.9316, -0.1335,  0.3415, -0.0716, -0.0909]])


In [55]:
print(f"Matrix multiplication A @ B shape: {(A @ B).shape}")

Matrix multiplication A @ B shape: torch.Size([4, 5])


In [61]:
print(f"Matrix multiplication A @ B:\n{A @ B}")

Matrix multiplication A @ B:
tensor([[ 1.3580,  0.5888, -1.8952,  0.9613, -0.1596],
        [ 2.2399, -0.6239,  0.1931, -0.8703, -0.5791],
        [-1.0636, -0.2757,  0.3299, -0.1344, -0.3312],
        [-0.6235,  0.6050, -0.1184,  0.5456,  0.7808]])


**Exercise 2: Normalize a tensor to have zero mean and unit variance**

In [65]:
tensor = torch.randn(100, 10)

In [76]:
print(tensor)

tensor([[-1.2389e+00, -1.1812e+00, -1.0318e-01,  1.6807e+00, -2.9093e-01,
         -1.9038e-01, -4.3973e-01,  8.9013e-01,  4.5068e-01,  8.2047e-01],
        [-7.4839e-01,  6.8000e-01, -1.4508e-01, -1.0368e-02, -4.8061e-01,
         -1.6556e-02, -6.0004e-01, -5.9534e-01, -4.3246e-01, -7.1259e-01],
        [-7.0029e-01,  1.2313e+00,  9.1771e-01, -8.5286e-02, -1.7139e+00,
          3.8805e-01, -4.6878e-02, -6.6701e-01,  2.8772e-01, -8.5422e-01],
        [ 7.5001e-01, -2.1544e+00, -1.8525e-01, -3.4355e-01, -9.8278e-01,
          1.4724e+00,  5.1843e-01,  1.1344e+00, -1.1047e+00,  3.9971e-01],
        [ 6.0474e-01,  9.9502e-02,  2.1674e-01, -7.4463e-01, -1.8894e+00,
          8.2298e-01, -1.4357e-02,  1.0571e+00, -1.0370e+00, -2.9757e-01],
        [-8.5172e-01,  2.8918e-01, -8.9324e-01,  1.8647e+00,  5.0715e-02,
          1.9659e-02, -1.2775e-01,  3.5776e-01, -1.1238e+00,  4.6559e-01],
        [-3.0510e+00,  8.5078e-01,  5.7983e-01,  2.4295e-01, -1.3800e+00,
         -3.6408e-01, -1.9835e-0

In [66]:
mean = tensor.mean()
mean

tensor(0.0152)

In [68]:
std = tensor.std()
std

tensor(0.9839)

In [75]:
normalized_tensor = (tensor - mean) / std
print(normalized_tensor)

tensor([[-1.2746e+00, -1.2160e+00, -1.2032e-01,  1.6928e+00, -3.1114e-01,
         -2.0894e-01, -4.6237e-01,  8.8927e-01,  4.4262e-01,  8.1847e-01],
        [-7.7609e-01,  6.7569e-01, -1.6290e-01, -2.5981e-02, -5.0393e-01,
         -3.2271e-02, -6.2531e-01, -6.2054e-01, -4.5499e-01, -7.3971e-01],
        [-7.2721e-01,  1.2360e+00,  9.1730e-01, -1.0213e-01, -1.7575e+00,
          3.7896e-01, -6.3090e-02, -6.9338e-01,  2.7699e-01, -8.8366e-01],
        [ 7.4685e-01, -2.2052e+00, -2.0373e-01, -3.6462e-01, -1.0143e+00,
          1.4811e+00,  5.1148e-01,  1.1375e+00, -1.1382e+00,  3.9081e-01],
        [ 5.9920e-01,  8.5688e-02,  2.0485e-01, -7.7227e-01, -1.9358e+00,
          8.2101e-01, -3.0036e-02,  1.0590e+00, -1.0694e+00, -3.1789e-01],
        [-8.8112e-01,  2.7847e-01, -9.2331e-01,  1.8798e+00,  3.6102e-02,
          4.5376e-03, -1.4529e-01,  3.4818e-01, -1.1577e+00,  4.5777e-01],
        [-3.1164e+00,  8.4927e-01,  5.7389e-01,  2.3148e-01, -1.4181e+00,
         -3.8549e-01, -2.1704e-0

In [77]:
normalized_tensor.mean()

tensor(-1.2398e-08)

In [78]:
normalized_tensor.std()

tensor(1.)

**Exercise 3: Find the indices of the top 3 values in a tensor**

In [80]:
tensor = torch.randn(10)
print(tensor)

tensor([-2.7704,  1.9610, -0.7328,  0.0113,  0.4797, -0.0365,  1.0878, -0.0177,
        -0.5193,  0.8134])


***Top 3 maximum values***

In [87]:
values, indices = torch.topk(tensor, k=3)
values, indices

(tensor([1.9610, 1.0878, 0.8134]), tensor([1, 6, 9]))

***Top 3 minimum values***

In [88]:
values, indices = torch.topk(tensor, k=3, largest=False)
values, indices

(tensor([-2.7704, -0.7328, -0.5193]), tensor([0, 2, 8]))

**Exercise 4: Implement softmax function**

In [90]:
logits = torch.randn(2, 5)
print(logits)

tensor([[-1.3440, -1.3025, -0.0280, -0.4115,  0.8032],
        [-0.9688,  0.1715, -0.5394, -0.9222, -0.7265]])


In [93]:
exp = torch.exp(logits)
print(exp)

tensor([[0.2608, 0.2718, 0.9724, 0.6627, 2.2327],
        [0.3796, 1.1871, 0.5831, 0.3977, 0.4836]])


In [94]:
sum_exp = sum(exp)
sum_exp

tensor([0.6403, 1.4589, 1.5555, 1.0603, 2.7163])

In [96]:
softmax = exp / sum_exp
print(softmax)

tensor([[0.4073, 0.1863, 0.6251, 0.6250, 0.8220],
        [0.5927, 0.8137, 0.3749, 0.3750, 0.1780]])


In [99]:
## Another way
softmax_another_way = torch.softmax(logits, dim=0)
print(softmax_another_way)

tensor([[0.4073, 0.1863, 0.6251, 0.6250, 0.8220],
        [0.5927, 0.8137, 0.3749, 0.3750, 0.1780]])


**Exercise 5: Compute cosine similarity between two vectors**

In [124]:
v1 = torch.randn(100)
v2 = torch.randn(100)

In [125]:
v1_dot_v2 = v1 @ v2

In [126]:
norm_v1_mul_v2 = torch.sqrt(v1 @ v1) * torch.sqrt(v2 @ v2)
norm_v1_mul_v2

tensor(100.9333)

In [127]:
cosine_similarity = v1_dot_v2 / norm_v1_mul_v2
cosine_similarity

tensor(0.0615)

In [128]:
## Another way
cosine_similarity_another_way = torch.dot(v1, v2) / (torch.norm(v1) * torch.norm(v2))
cosine_similarity_another_way

tensor(0.0615)

In [131]:
cosine_similarity_another_way_available = torch.cosine_similarity(v1, v2, dim=0)
cosine_similarity_another_way_available

tensor(0.0615)