# Exercise 3: Tensor Manipulation
PyTorch Fundamentals - Module 1

This exercise covers:
- Reshaping tensors
- Indexing and slicing
- Transposing and permuting
- Squeezing and unsqueezing
- Concatenating and splitting tensors

PyTorch 2.0 Note: All manipulation operations are compatible with PyTorch 2.0.
See the device management section for torch.set_default_device() (PyTorch 2.0+ feature).

In [80]:
import torch

torch.manual_seed(42)

## Part 1: Reshaping

**Create a 1D tensor**

In [2]:
x = torch.arange(12)
print(f"Original tensor: {x}")
print(f"Original shape: {x.shape}")

Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Original shape: torch.Size([12])


**Reshape to 3x4**

In [3]:
reshaped = x.reshape(3, 4)
print(f"\nReshaped to (3, 4):\n{reshaped}")


Reshaped to (3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


**Reshape to 2x6**

In [4]:
reshaped_2x6 = x.reshape(2, 6)
print(f"\nReshaped to (2, 6):\n{reshaped_2x6}")


Reshaped to (2, 6):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


**Flatten a 2D tensor**

In [5]:
flat = reshaped.flatten()
print(f"\nFlattened: {flat}")


Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


**Reshape with view (only works on contiguous tensors)**

In [8]:
viewed = reshaped.view(-1)  # -1 means infer dimension
print(f"\nViewed as 1D: {viewed}")


Viewed as 1D: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


## Part 2: Squeeze and Unsqueeze

**Create tensor with singleton dimensions**

In [21]:
x = torch.randn(2, 1, 4, 1)
print(f"Original shape: {x.shape}")
print(x)

Original shape: torch.Size([2, 1, 4, 1])
tensor([[[[ 0.2815],
          [ 0.0562],
          [ 0.5227],
          [-0.2384]]],


        [[[-0.0499],
          [ 0.5263],
          [-0.0085],
          [ 0.7291]]]])


**Remove all singleton dimensions**

In [22]:
squeezed = x.squeeze()
print(f"After squeeze: {squeezed.shape}")
print(squeezed)

After squeeze: torch.Size([2, 4])
tensor([[ 0.2815,  0.0562,  0.5227, -0.2384],
        [-0.0499,  0.5263, -0.0085,  0.7291]])


**Remove specific singleton dimension**

In [25]:
squeezed_dim = x.squeeze(dim=1)
print(f"After squeeze(dim=1): {squeezed_dim.shape}")
squeezed_dim

After squeeze(dim=1): torch.Size([2, 4, 1])


tensor([[[ 0.2815],
         [ 0.0562],
         [ 0.5227],
         [-0.2384]],

        [[-0.0499],
         [ 0.5263],
         [-0.0085],
         [ 0.7291]]])

**Add dimension at position 0**

In [26]:
unsqueezed_0 = squeezed.unsqueeze(dim=0)
print(f"\nAfter unsqueeze(dim=0): {unsqueezed_0.shape}")
unsqueezed_0


After unsqueeze(dim=0): torch.Size([1, 2, 4])


tensor([[[ 0.2815,  0.0562,  0.5227, -0.2384],
         [-0.0499,  0.5263, -0.0085,  0.7291]]])

**Add dimension at last position**

In [27]:
unsqueezed_last = squeezed.unsqueeze(dim=-1)
print(f"After unsqueeze(dim=-1): {unsqueezed_last.shape}")
unsqueezed_last

After unsqueeze(dim=-1): torch.Size([2, 4, 1])


tensor([[[ 0.2815],
         [ 0.0562],
         [ 0.5227],
         [-0.2384]],

        [[-0.0499],
         [ 0.5263],
         [-0.0085],
         [ 0.7291]]])

## Part 3: Transpose and Permute

**Create a 3D tensor**

In [28]:
x = torch.randn(2, 3, 4)
print(f"Original shape: {x.shape}")
x

Original shape: torch.Size([2, 3, 4])


tensor([[[ 1.4451,  0.8564,  2.2181,  0.5232],
         [ 0.3466, -0.1973, -1.0546,  1.2780],
         [ 0.7281, -0.7106, -0.6021,  0.9604]],

        [[ 0.4048, -1.3543, -0.4976,  0.4747],
         [-0.1976,  1.2683,  1.2243,  0.0981],
         [ 1.7423, -1.3527,  0.2191,  0.5526]]])

**Transpose dimensions 0 and 1**

In [29]:
transposed = torch.transpose(x, 0, 1)
print(f"After transpose(0, 1): {transposed.shape}")
transposed

After transpose(0, 1): torch.Size([3, 2, 4])


tensor([[[ 1.4451,  0.8564,  2.2181,  0.5232],
         [ 0.4048, -1.3543, -0.4976,  0.4747]],

        [[ 0.3466, -0.1973, -1.0546,  1.2780],
         [-0.1976,  1.2683,  1.2243,  0.0981]],

        [[ 0.7281, -0.7106, -0.6021,  0.9604],
         [ 1.7423, -1.3527,  0.2191,  0.5526]]])

**Permute all dimensions**

In [30]:
permuted = x.permute(2, 0, 1)
print(f"After permute(2, 0, 1): {permuted.shape}")
permuted

After permute(2, 0, 1): torch.Size([4, 2, 3])


tensor([[[ 1.4451,  0.3466,  0.7281],
         [ 0.4048, -0.1976,  1.7423]],

        [[ 0.8564, -0.1973, -0.7106],
         [-1.3543,  1.2683, -1.3527]],

        [[ 2.2181, -1.0546, -0.6021],
         [-0.4976,  1.2243,  0.2191]],

        [[ 0.5232,  1.2780,  0.9604],
         [ 0.4747,  0.0981,  0.5526]]])

**Matrix transpose for 2D tensor**

In [58]:
matrix = torch.randn(3, 4)
print(f"\nMatrix shape: {matrix.shape}")
print(f"Matrix.T shape: {matrix.T.shape}")


Matrix shape: torch.Size([3, 4])
Matrix.T shape: torch.Size([4, 3])


## Part 4: Indexing and Slicing

**Create a 2D tensor**

In [35]:
x = torch.arange(20).reshape(4, 5)
print(f"Tensor:\n{x}")

Tensor:
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


**Get element at position (1, 2)**

In [38]:
element = x[1, 2]
print(f"\nElement at [1, 2]: {element}")


Element at [1, 2]: 7


**Get first row**

In [39]:
first_row = x[0, :]
print(f"\nFirst row: {first_row}")


First row: tensor([0, 1, 2, 3, 4])


**Get last column**

In [40]:
last_col = x[:, -1]
print(f"Last column: {last_col}")

Last column: tensor([ 4,  9, 14, 19])


**Get submatrix (rows 1-2, cols 2-4)**

In [41]:
submatrix = x[1:3, 2:5]
print(f"\nSubmatrix [1:3, 2:5]:\n{submatrix}")


Submatrix [1:3, 2:5]:
tensor([[ 7,  8,  9],
        [12, 13, 14]])


**Boolean indexing**

In [44]:
values = x[x > 10]
print(f"\nValues > 10: {values}")


Values > 10: tensor([11, 12, 13, 14, 15, 16, 17, 18, 19])


## Part 5: Concatenating and Splitting

**Create tensors to concatenate**

In [46]:
x1 = torch.randn(2, 3)
x2 = torch.randn(2, 3)
x3 = torch.randn(2, 3)

In [47]:
print(f"x1 shape: {x1.shape}")
print(f"x2 shape: {x2.shape}")

x1 shape: torch.Size([2, 3])
x2 shape: torch.Size([2, 3])


**Stack along new dimension (dim=0)**

In [49]:
stacked = torch.stack([x1, x2, x3], dim=0)
print(f"\nStacked along dim=0: {stacked.shape}")
stacked


Stacked along dim=0: torch.Size([3, 2, 3])


tensor([[[ 1.1351,  0.7592, -3.5945],
         [ 0.0192,  0.1052,  0.9603]],

        [[-0.5672, -0.5706,  1.5980],
         [ 0.1115, -0.0392,  1.4112]],

        [[-0.6556,  0.8576, -1.6270],
         [-1.3951, -0.2387, -0.5050]]])

**Concatenate along existing dimension (dim=0)**

In [51]:
concat_dim0 = torch.cat([x1, x2, x3], dim=0)
print(f"Concatenated along dim=0: {concat_dim0.shape}")
print(concat_dim0)

Concatenated along dim=0: torch.Size([6, 3])
tensor([[ 1.1351,  0.7592, -3.5945],
        [ 0.0192,  0.1052,  0.9603],
        [-0.5672, -0.5706,  1.5980],
        [ 0.1115, -0.0392,  1.4112],
        [-0.6556,  0.8576, -1.6270],
        [-1.3951, -0.2387, -0.5050]])


**Split tensor into chunks**

In [52]:
x = torch.randn(6, 4)
chunks = torch.chunk(x, chunks=3, dim=0)
print(f"\nSplit into 3 chunks along dim=0:")
for i, chunk in enumerate(chunks):
    print(f"  Chunk {i} shape: {chunk.shape}")


Split into 3 chunks along dim=0:
  Chunk 0 shape: torch.Size([2, 4])
  Chunk 1 shape: torch.Size([2, 4])
  Chunk 2 shape: torch.Size([2, 4])


In [56]:
print(x)

tensor([[ 1.4805,  0.3449, -1.4241, -0.1163],
        [-0.9727,  0.9585,  1.6192,  1.4506],
        [ 0.2868, -0.7308,  0.1748, -1.0939],
        [ 0.9633, -0.3095,  0.5712,  1.1179],
        [-1.5469,  0.7567,  0.7755,  2.0265],
        [ 0.9812, -0.6401, -0.4908,  0.2080]])


In [54]:
chunks

(tensor([[ 1.4805,  0.3449, -1.4241, -0.1163],
         [-0.9727,  0.9585,  1.6192,  1.4506]]),
 tensor([[ 0.2868, -0.7308,  0.1748, -1.0939],
         [ 0.9633, -0.3095,  0.5712,  1.1179]]),
 tensor([[-1.5469,  0.7567,  0.7755,  2.0265],
         [ 0.9812, -0.6401, -0.4908,  0.2080]]))

## Exercises

**Exercise 1: Given a tensor of shape (64, 1, 28, 28), remove the singleton dimension**

In [57]:
x = torch.randn(64, 1, 28, 28)

In [62]:
squeezed_dim = x.squeeze(dim=1)
print(f"After squeeze: {squeezed_dim.shape}")

After squeeze: torch.Size([64, 28, 28])


**Exercise 2: Add a batch dimension to a single image tensor of shape (3, 224, 224)**

In [63]:
image = torch.randn(3, 224, 224)

In [64]:
unsqueezed_0 = image.unsqueeze(dim=0)
print(f"\nAfter unsqueeze(dim=0): {unsqueezed_0.shape}")


After unsqueeze(dim=0): torch.Size([1, 3, 224, 224])


**Exercise 3: Convert HWC format to CHW format**

In [65]:
hwc_image = torch.randn(224, 224, 3)

In [73]:
transposed = hwc_image.permute(2, 0, 1)
transposed.shape

torch.Size([3, 224, 224])

**Exercise 4: Extract the diagonal elements from a square matrix**

In [74]:
matrix = torch.randn(5, 5)

In [77]:
print(matrix)

tensor([[-0.5845,  0.2172, -1.6177,  0.3741,  0.6648],
        [ 1.8872, -0.0236, -0.6799, -1.1706,  1.9445],
        [-1.1796,  0.0226, -1.9896, -1.0474,  0.8641],
        [-0.3156, -2.0637, -0.4660, -0.2924, -0.0408],
        [ 0.2585, -0.5560,  0.4550,  0.2495, -0.1237]])


In [75]:
diagonal_element = matrix.diagonal()
diagonal_element

tensor([-0.5845, -0.0236, -1.9896, -0.2924, -0.1237])

**Exercise 5: Create a batch of 10 random images and stack them**

In [78]:
images = [torch.randn(3, 224, 224) for _ in range(10)]

In [90]:
stacked = torch.stack(images, dim=0)
stacked.shape

torch.Size([10, 3, 224, 224])